version: "3"
volumes:
  node_modules:
  deps:
services:
  backend:
    build:
      target: dev
    volumes:
      - .:/app
      - build:/app/_build
      - deps:/app/deps
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    entrypoint: /app/docker-entrypoint.sh
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
