version: "3"
networks:
  pluto:
volumes:
  db_data:
  shared_data:
  build:
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - pluto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  backend:
    image: public.ecr.aws/r0i5o1h0/pluto_backend:latest
    entrypoint: /app/entrypoint.yml
    command: ["bin/pluto", "start"]
    env_file:
      - .env
    networks:
      - pluto
    depends_on:
      - db
  frontend:
    image: public.ecr.aws/r0i5o1h0/pluto_frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - pluto
  nginx:
    image: public.ecr.aws/r0i5o1h0/pluto_nginx:latest
    ports:
      - 80:80
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - pluto
    depends_on:
      - frontend
      - backend
