version: "3"
networks:
  pluto:
volumes:
  db_data:
  shared_data:
  build:
  node_modules:
  deps:
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - pluto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: .
    volumes:
      - .:/app
      - build:/app/_build
      - deps:/app/deps
    ports:
      - 4000:4000
    networks:
      - pluto
    environment:
      DB_HOST: db
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    entrypoint: /app/docker-entrypoint.sh
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    networks:
      - pluto
    stdin_open: true
    tty: true
