version: "3"
services:
  backend:
    build:
      target: dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    volumes:
      - ./frontend/:/app
    entrypoint: /app/docker-entrypoint.sh
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
