version: "3"
networks:
  pluto:
volumes:
  db_data:
  shared_data:
  build:
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - pluto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: .
      dockerfile: .circleci/images/Dockerfile.backend
      args:
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: ["bin/pluto", "start"]
    networks:
      - pluto
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../.circleci/images/Dockerfile.frontend
      args:
        API_URL: ${API_URL}
        SOCKET_URL: ${SOCKET_URL}
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - pluto
  nginx:
    build:
      context: .circleci/nginx/
      dockerfile: ../images/Dockerfile.nginx
    ports:
      - 80:80
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - pluto
    depends_on:
      - frontend
      - backend
