version: "3"
networks:
  pluto:
volumes:
  db_data:
  shared_data:
  deps:
  node_modules:
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - pluto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: .
    volumes:
      - deps:/app/deps
    networks:
      - pluto
  frontend:
    build:
      context: ./frontend/
    volumes:
      - node_modules:/app/node_modules
    networks:
      - pluto
