version: "3"
volumes:
  e2e_node_modules:
services:
  backend:
    build:
      target: dev
    ports:
      - 4000:4000
    volumes:
      - build:/app/_build
    environment:
      DB_HOST: db
    env_file:
      - e2e/.env
    depends_on:
      - db
    command: ["mix", "do", "ecto.drop,", "ecto.create,", "ecto.migrate,", "phx.server"]
  frontend:
    build:
      args:
        API_URL: http://localhost:4000
        SOCKET_URL: ws://localhost:4000/socket
      target: prod
    ports:
      - 4001:80
    command: ["nginx", "-g", "daemon off;"]
