version: "3"
volumes:
  e2e_node_modules:
services:
  backend:
    build:
      target: dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    env_file:
      - e2e/.env
    depends_on:
      - db
    command: ["mix", "do", "ecto.drop,", "ecto.create,", "ecto.migrate,", "phx.server"]
  frontend:
    build:
      args:
        API_URL: http://backend:4000
        SOCKET_URL: ws://backend:4000/socket
      target: prod
    ports:
      - 3000:80
    command: ["nginx", "-g", "daemon off;"]
  e2e:
    build:
      context: ./e2e/
    volumes:
      - e2e_node_modules:/app/node_modules
    networks:
      - pluto
    environment:
      CYPRESS_BASE_URL: http://frontend
      CYPRESS_API_URL: http://backend:4000
    depends_on:
      - backend
      - frontend
    entrypoint: /app/docker-entrypoint.sh
    command: ["yarn", "cypress", "run"]
