services:
  backend:
    build:
      args:
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      target: prod
    ports:
      - 4000:4000
    command: ["bin/pluto", "start"]
