version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: .circleci/images/Dockerfile.backend
      args:
        DB_USER: ${PGUSER}
        DB_PASS: ${PGPASSWORD}
        DB_HOST: ${PGHOST}
        DB_NAME: ${PGDATABASE}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../.circleci/images/Dockerfile.frontend
      args:
        API_URL: ${API_URL}
        SOCKET_URL: ${SOCKET_URL}
  nginx:
    build:
      context: .circleci/nginx/
      dockerfile: ../images/Dockerfile.nginx
