version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.4
        environment:
          MIX_ENV: test
      - image: circleci/postgres:13.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pluto_test
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix credo
      - run: mix test

      - store_test_results:
          path: _build/test/lib/pluto
